/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedBatchesIndexRouteImport } from './routes/_authed/batches/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedBatchesNewRouteImport } from './routes/_authed/batches/new'
import { Route as AuthedBatchesBatchIdIndexRouteImport } from './routes/_authed/batches/$batchId/index'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users/index'
import { Route as AuthedAdminProjectsIndexRouteImport } from './routes/_authed/admin/projects/index'
import { Route as AuthedBatchesBatchIdWarningRouteImport } from './routes/_authed/batches/$batchId/warning'
import { Route as AuthedAdminUsersNewRouteImport } from './routes/_authed/admin/users/new'
import { Route as AuthedAdminProjectsNewRouteImport } from './routes/_authed/admin/projects/new'
import { Route as AuthedAdminUsersUserIdIndexRouteImport } from './routes/_authed/admin/users/$userId/index'
import { Route as AuthedAdminProjectsProjectIdIndexRouteImport } from './routes/_authed/admin/projects/$projectId/index'
import { Route as AuthedAdminProjectsProjectIdTowersNewRouteImport } from './routes/_authed/admin/projects/$projectId/towers/new'
import { Route as AuthedAdminProjectsProjectIdTowersTowerIdIndexRouteImport } from './routes/_authed/admin/projects/$projectId/towers/$towerId/index'
import { Route as AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRouteImport } from './routes/_authed/admin/projects/$projectId/towers/$towerId/apartments/new'
import { Route as AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRouteImport } from './routes/_authed/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBatchesIndexRoute = AuthedBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedBatchesNewRoute = AuthedBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBatchesBatchIdIndexRoute =
  AuthedBatchesBatchIdIndexRouteImport.update({
    id: '/batches/$batchId/',
    path: '/batches/$batchId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminProjectsIndexRoute =
  AuthedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedBatchesBatchIdWarningRoute =
  AuthedBatchesBatchIdWarningRouteImport.update({
    id: '/batches/$batchId/warning',
    path: '/batches/$batchId/warning',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminUsersNewRoute = AuthedAdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminProjectsNewRoute = AuthedAdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersUserIdIndexRoute =
  AuthedAdminUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminProjectsProjectIdIndexRoute =
  AuthedAdminProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminProjectsProjectIdTowersNewRoute =
  AuthedAdminProjectsProjectIdTowersNewRouteImport.update({
    id: '/projects/$projectId/towers/new',
    path: '/projects/$projectId/towers/new',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute =
  AuthedAdminProjectsProjectIdTowersTowerIdIndexRouteImport.update({
    id: '/projects/$projectId/towers/$towerId/',
    path: '/projects/$projectId/towers/$towerId/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute =
  AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRouteImport.update({
    id: '/projects/$projectId/towers/$towerId/apartments/new',
    path: '/projects/$projectId/towers/$towerId/apartments/new',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute =
  AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRouteImport.update(
    {
      id: '/projects/$projectId/towers/$towerId/apartments/$apartmentId/',
      path: '/projects/$projectId/towers/$towerId/apartments/$apartmentId/',
      getParentRoute: () => AuthedAdminRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/batches/new': typeof AuthedBatchesNewRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/batches/': typeof AuthedBatchesIndexRoute
  '/admin/projects/new': typeof AuthedAdminProjectsNewRoute
  '/admin/users/new': typeof AuthedAdminUsersNewRoute
  '/batches/$batchId/warning': typeof AuthedBatchesBatchIdWarningRoute
  '/admin/projects/': typeof AuthedAdminProjectsIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/batches/$batchId/': typeof AuthedBatchesBatchIdIndexRoute
  '/admin/projects/$projectId/': typeof AuthedAdminProjectsProjectIdIndexRoute
  '/admin/users/$userId/': typeof AuthedAdminUsersUserIdIndexRoute
  '/admin/projects/$projectId/towers/new': typeof AuthedAdminProjectsProjectIdTowersNewRoute
  '/admin/projects/$projectId/towers/$towerId/': typeof AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute
  '/admin/projects/$projectId/towers/$towerId/apartments/new': typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute
  '/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/': typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/batches/new': typeof AuthedBatchesNewRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/batches': typeof AuthedBatchesIndexRoute
  '/admin/projects/new': typeof AuthedAdminProjectsNewRoute
  '/admin/users/new': typeof AuthedAdminUsersNewRoute
  '/batches/$batchId/warning': typeof AuthedBatchesBatchIdWarningRoute
  '/admin/projects': typeof AuthedAdminProjectsIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
  '/batches/$batchId': typeof AuthedBatchesBatchIdIndexRoute
  '/admin/projects/$projectId': typeof AuthedAdminProjectsProjectIdIndexRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdIndexRoute
  '/admin/projects/$projectId/towers/new': typeof AuthedAdminProjectsProjectIdTowersNewRoute
  '/admin/projects/$projectId/towers/$towerId': typeof AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute
  '/admin/projects/$projectId/towers/$towerId/apartments/new': typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute
  '/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId': typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/batches/new': typeof AuthedBatchesNewRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/batches/': typeof AuthedBatchesIndexRoute
  '/_authed/admin/projects/new': typeof AuthedAdminProjectsNewRoute
  '/_authed/admin/users/new': typeof AuthedAdminUsersNewRoute
  '/_authed/batches/$batchId/warning': typeof AuthedBatchesBatchIdWarningRoute
  '/_authed/admin/projects/': typeof AuthedAdminProjectsIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/_authed/batches/$batchId/': typeof AuthedBatchesBatchIdIndexRoute
  '/_authed/admin/projects/$projectId/': typeof AuthedAdminProjectsProjectIdIndexRoute
  '/_authed/admin/users/$userId/': typeof AuthedAdminUsersUserIdIndexRoute
  '/_authed/admin/projects/$projectId/towers/new': typeof AuthedAdminProjectsProjectIdTowersNewRoute
  '/_authed/admin/projects/$projectId/towers/$towerId/': typeof AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute
  '/_authed/admin/projects/$projectId/towers/$towerId/apartments/new': typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute
  '/_authed/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/': typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/batches/new'
    | '/admin/'
    | '/batches/'
    | '/admin/projects/new'
    | '/admin/users/new'
    | '/batches/$batchId/warning'
    | '/admin/projects/'
    | '/admin/users/'
    | '/batches/$batchId/'
    | '/admin/projects/$projectId/'
    | '/admin/users/$userId/'
    | '/admin/projects/$projectId/towers/new'
    | '/admin/projects/$projectId/towers/$towerId/'
    | '/admin/projects/$projectId/towers/$towerId/apartments/new'
    | '/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/batches/new'
    | '/admin'
    | '/batches'
    | '/admin/projects/new'
    | '/admin/users/new'
    | '/batches/$batchId/warning'
    | '/admin/projects'
    | '/admin/users'
    | '/batches/$batchId'
    | '/admin/projects/$projectId'
    | '/admin/users/$userId'
    | '/admin/projects/$projectId/towers/new'
    | '/admin/projects/$projectId/towers/$towerId'
    | '/admin/projects/$projectId/towers/$towerId/apartments/new'
    | '/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/'
    | '/_authed/batches/new'
    | '/_authed/admin/'
    | '/_authed/batches/'
    | '/_authed/admin/projects/new'
    | '/_authed/admin/users/new'
    | '/_authed/batches/$batchId/warning'
    | '/_authed/admin/projects/'
    | '/_authed/admin/users/'
    | '/_authed/batches/$batchId/'
    | '/_authed/admin/projects/$projectId/'
    | '/_authed/admin/users/$userId/'
    | '/_authed/admin/projects/$projectId/towers/new'
    | '/_authed/admin/projects/$projectId/towers/$towerId/'
    | '/_authed/admin/projects/$projectId/towers/$towerId/apartments/new'
    | '/_authed/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/batches/': {
      id: '/_authed/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof AuthedBatchesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/batches/new': {
      id: '/_authed/batches/new'
      path: '/batches/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof AuthedBatchesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/batches/$batchId/': {
      id: '/_authed/batches/$batchId/'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId/'
      preLoaderRoute: typeof AuthedBatchesBatchIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/': {
      id: '/_authed/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/batches/$batchId/warning': {
      id: '/_authed/batches/$batchId/warning'
      path: '/batches/$batchId/warning'
      fullPath: '/batches/$batchId/warning'
      preLoaderRoute: typeof AuthedBatchesBatchIdWarningRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/new': {
      id: '/_authed/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthedAdminUsersNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/new': {
      id: '/_authed/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AuthedAdminProjectsNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users/$userId/': {
      id: '/_authed/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/$projectId/': {
      id: '/_authed/admin/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/admin/projects/$projectId/'
      preLoaderRoute: typeof AuthedAdminProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/$projectId/towers/new': {
      id: '/_authed/admin/projects/$projectId/towers/new'
      path: '/projects/$projectId/towers/new'
      fullPath: '/admin/projects/$projectId/towers/new'
      preLoaderRoute: typeof AuthedAdminProjectsProjectIdTowersNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/$projectId/towers/$towerId/': {
      id: '/_authed/admin/projects/$projectId/towers/$towerId/'
      path: '/projects/$projectId/towers/$towerId'
      fullPath: '/admin/projects/$projectId/towers/$towerId/'
      preLoaderRoute: typeof AuthedAdminProjectsProjectIdTowersTowerIdIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/$projectId/towers/$towerId/apartments/new': {
      id: '/_authed/admin/projects/$projectId/towers/$towerId/apartments/new'
      path: '/projects/$projectId/towers/$towerId/apartments/new'
      fullPath: '/admin/projects/$projectId/towers/$towerId/apartments/new'
      preLoaderRoute: typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/': {
      id: '/_authed/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/'
      path: '/projects/$projectId/towers/$towerId/apartments/$apartmentId'
      fullPath: '/admin/projects/$projectId/towers/$towerId/apartments/$apartmentId/'
      preLoaderRoute: typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminProjectsNewRoute: typeof AuthedAdminProjectsNewRoute
  AuthedAdminUsersNewRoute: typeof AuthedAdminUsersNewRoute
  AuthedAdminProjectsIndexRoute: typeof AuthedAdminProjectsIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
  AuthedAdminProjectsProjectIdIndexRoute: typeof AuthedAdminProjectsProjectIdIndexRoute
  AuthedAdminUsersUserIdIndexRoute: typeof AuthedAdminUsersUserIdIndexRoute
  AuthedAdminProjectsProjectIdTowersNewRoute: typeof AuthedAdminProjectsProjectIdTowersNewRoute
  AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute: typeof AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute
  AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute: typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute
  AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute: typeof AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminProjectsNewRoute: AuthedAdminProjectsNewRoute,
  AuthedAdminUsersNewRoute: AuthedAdminUsersNewRoute,
  AuthedAdminProjectsIndexRoute: AuthedAdminProjectsIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
  AuthedAdminProjectsProjectIdIndexRoute:
    AuthedAdminProjectsProjectIdIndexRoute,
  AuthedAdminUsersUserIdIndexRoute: AuthedAdminUsersUserIdIndexRoute,
  AuthedAdminProjectsProjectIdTowersNewRoute:
    AuthedAdminProjectsProjectIdTowersNewRoute,
  AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute:
    AuthedAdminProjectsProjectIdTowersTowerIdIndexRoute,
  AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute:
    AuthedAdminProjectsProjectIdTowersTowerIdApartmentsNewRoute,
  AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute:
    AuthedAdminProjectsProjectIdTowersTowerIdApartmentsApartmentIdIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBatchesNewRoute: typeof AuthedBatchesNewRoute
  AuthedBatchesIndexRoute: typeof AuthedBatchesIndexRoute
  AuthedBatchesBatchIdWarningRoute: typeof AuthedBatchesBatchIdWarningRoute
  AuthedBatchesBatchIdIndexRoute: typeof AuthedBatchesBatchIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBatchesNewRoute: AuthedBatchesNewRoute,
  AuthedBatchesIndexRoute: AuthedBatchesIndexRoute,
  AuthedBatchesBatchIdWarningRoute: AuthedBatchesBatchIdWarningRoute,
  AuthedBatchesBatchIdIndexRoute: AuthedBatchesBatchIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
